x-watch-path-coolify:
  - "deploy/svc/Dockerfile"
  - "deploy/svc/docker-compose.yaml"
  - "deploy/svc/docker-compose.coolify.yaml"
  - "deploy/svc/Dockerfile.dockerignore"
  - "pyproject.toml"
  - "uv.lock"
  - "README.md"
  - "LICENSE"
  - ".python-version"
  - "services/**"
  - "scripts/**"

services:
  briareus-svc:
    extends:
      file: docker-compose.yaml
      service: briareus-svc
    environment:
      TZ: "${TZ:-UTC}"
      OTLP_ENDPOINT: "${OTLP_ENDPOINT:-}"
      OTLP_BEARER_TOKEN: "${OTLP_BEARER_TOKEN:-}"
      OTEL_SERVICE_NAMESPACE: "${OTEL_SERVICE_NAMESPACE:?}"
      OTEL_DEPLOYMENT_ENVIRONMENT_NAME: "${OTEL_DEPLOYMENT_ENVIRONMENT_NAME:?}"
      OTEL_SERVICE_NAME: "${OTEL_SERVICE_NAME:?}"
networks:
  briareus:
    external: true
    name: briareus-net
